### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by Pastor111** [RogyDev/Rogy-Engine-#2]
Do you have any instructions on how to run (or build) the engine?😅

**Comment by RogyDev** [comment]
Sorry for not providing any instructions for building the project because it is in its early stages
Just clone the repository and build with visual studio 2015/17 to run it.

**Comment by Pastor111** [comment]
Can i use visual studio 19?

**Comment by RogyDev** [comment]
Yes

**Comment by Pastor111** [comment]
Okay i am going to try it out

**Comment by Pastor111** [comment]
![image](https://user-images.githubusercontent.com/64261346/145092024-dedb7c1a-842f-47c8-8487-800c8c333dff.png)

I get this errors when i run it in Release x86

**Comment by RogyDev** [comment]
Try including "string" to Skeleton.h

**Comment by Pastor111** [comment]
![image](https://user-images.githubusercontent.com/64261346/145152436-6165ef99-c5eb-4415-83f3-cb2fcca5ae47.png)
Now i am left with this 2

**Comment by RogyDev** [comment]
Hi sorry for my late response, I don't have vs2019 at the moment but please try this solution https://stackoverflow.com/questions/62256738/visual-studio-2019-c-and-stdfilesystem
"To switch to C++17' std::filesystem in Visual Studio ......."

change "std::experimental::filesystem" to "std::filesystem" in project_browser.cpp - line 609
https://github.com/RogyDev/Rogy-Engine-/blob/fa85d501b813c6492046e15dce50521f817a244d/Rogy/Engine/editor/project_browser.cpp#L609
